### ISSUE TITLE
 Runesmith Class Feats not appearing in Compendium Browser 

### ISSUE THREAD

**Issue by ChrisHoward4682** [TikaelSol/pf2e-playtest-data#29]
Feats are visible in Impossible Playtest Compendium, and dragging feat into character sheet works properly, but feats are not discoverable through Compendium Browser through character sheet

**Comment by TikaelSol** [comment]
Not a module issue. On PF2e 6.7 and lower you need to enable the compendiums in the compendium browser settings tab. As of PF2e 6.8 the system defaults new compendiums to enabled instead of disabled.
