### ISSUE TITLE
Expert Necromancy, Master Necromancy, Legendary Necromancy not working

### ISSUE THREAD

**Issue by ravensblood95** [TikaelSol/pf2e-playtest-data#30]
The class features for Expert Necromancy, Master Necromancy, Legendary Necromancy only raise the proficiency level of the spell casting DC. They are not targeting the Necromancer class DC, and the Necromancer isn't listed as a class DC that can be targeted when trying to edit the effect.

![Capture 2](https://github.com/user-attachments/assets/49eede0c-64d9-4e6b-926b-e66392242baf)
![Capture 3](https://github.com/user-attachments/assets/ff48804a-793b-48bc-8c33-8fabd9550251)
![Capture](https://github.com/user-attachments/assets/c3c3793e-0a5e-47bc-8929-bbd3158ef2e5)

**Comment by TikaelSol** [comment]
Those features don't increase your class DC. Casters are stuck at trained the entire time
